"""connect.py - Module contains class to interact with Amazon Connect CCP APIs"""

import os
from typing import Any, Dict, Optional
from logging import Logger
import boto3
from chat_clients.common.logging_helper import get_logger
from chat_clients.common.session_helper import get_boto3_session, get_boto3_client_config, get_session_id
from chat_clients.common.locale_helper import Locale
from chat_clients.common.types import UserChatClientType

class AmazonConnectClient:
    """
    Class contains client code that establishes connection with Amazon Connect
    CCP flow API.  It calls the following Connect APIs:
    - StartChatContact
    - StartContactStreaming

    """
    # class constants
    DEFAULT_LOCALE = "en_US"
    DEFAULT_USER_CHAT_CLIENT_TYPE = UserChatClientType.WEB.value

    # connect variables
    client: boto3.client = None
    instance_id: str = None
    contact_flow_id: str = None
    streaming_arn: str = None
    user_chat_client_type: str = DEFAULT_USER_CHAT_CLIENT_TYPE

    # logger
    logger: Logger = None

    def __init__(self):
        # configure logger
        self.logger = get_logger(f"{__name__}.{type(self).__name__}")

        # initialize environment
        self.__init_env()

        # configure boto3 session
        boto3_session = get_boto3_session()
        boto3_client_config = get_boto3_client_config()
        self.client = boto3_session.client(
            'connect',
            config=boto3_client_config)

    def __init_env(self):
        """
        Read values from environment variables
        """
        self.instance_id = os.environ.get("CONNECT_INSTANCE_ID", default=None)
        if not self.instance_id or len(self.instance_id) <= 0:
            error_message = "CONNECT_INSTANCE_ID environment variable must be set"
            self.logger.error(error_message)
            raise ValueError(error_message)

        self.contact_flow_id = os.environ.get("CONNECT_CONTACT_FLOW_ID", default=None)
        if not self.contact_flow_id or len(self.contact_flow_id) <= 0:
            error_message = "CONNECT_CONTACT_FLOW_ID environment variable must be set"
            self.logger.error(error_message)
            raise ValueError(error_message)

        self.streaming_arn = os.environ.get("STREAMING_ENDPOINT_ARN", default=None)
        if not self.streaming_arn or len(self.streaming_arn) <= 0:
            error_message = "STREAMING_ENDPOINT_ARN environment variable must be set"
            self.logger.error(error_message)
            raise ValueError(error_message)

        # validate USER_CHAT_CLIENT_TYPE contains enumeration defined in UserChatClientType
        user_chat_client_type = os.environ.get("USER_CHAT_CLIENT_TYPE", None)
        if user_chat_client_type and UserChatClientType.is_valid(user_chat_client_type.upper()):
            self.user_chat_client_type = os.environ.get("USER_CHAT_CLIENT_TYPE").upper()

    def connect(self, session_id: Optional[str] = None, locale: Optional[str] = None, user_name: Optional[str] = None) -> Dict[str, Any]:
        """
        Establish connection with Amazon Connect using to enable real-time
        chat message streaming.  Refer to following documentation:
        https://docs.aws.amazon.com/connect/latest/adminguide/chat-message-streaming.html

        Method response is a dictionary containing results from both start_chat_contact
        and start_contact_streaming API calls.

        {
            contact_id": "",
            "participant_id": "",
            "participant_token": "",
            "streaming_id": ""
        }

        Args:
            session_id (str): Session ID used to track chat session.  If not provided,
                              then session ID will be generated by calling get_session_id()
            locale (str): Locale used to determine language used in chat.  If not provided,
                          then default locale will be used.
            user_name (str): User name used to identify user in chat.  If not provided,
                             then default user name will be used.

        Returns:
            Dict[str, Any]: A simplified response from both start_chat_contact and start_contact_streaming
        """
        # set class variables
        _session_id = session_id if session_id else get_session_id()
        _locale = Locale(locale) if locale else Locale(self.DEFAULT_LOCALE)
        _user_name = user_name if user_name else "User"

        # Step 1: Call the Amazon Connect StartChatContact API to initiate the chat contact.
        # Step 2: Keep track of ContactId and ParticipantToken from the StartChatContact response
        start_chat_contact_response = self.client.start_chat_contact(
            InstanceId=self.instance_id,
            ContactFlowId=self.contact_flow_id,
            Attributes={
                "locale": _locale.get_locale(),
                "session_id": _session_id
            },
            ParticipantDetails={
                "DisplayName": _user_name
            }
        )

        contact_id = start_chat_contact_response.get("ContactId", None)
        participant_id = start_chat_contact_response.get("ParticipantId", None)
        participant_token = start_chat_contact_response.get("ParticipantToken", None)
        continued_from_contact_id = start_chat_contact_response.get("ContinuedFromContactId", None)
        self.logger.debug("StartChatContact response attributes: ContactId: '%s', ParticipantId: '%s', ContinuedFromContactId: %s",
            contact_id,
            participant_id,
            continued_from_contact_id
        )
        self.logger.debug("StartChatContact response: %s", start_chat_contact_response)

        # if self.user_chat_client_type is not WEB, then call start_contact_streaming
        streaming_id = None
        if self.user_chat_client_type != UserChatClientType.WEB.value:

            # Step 3: Call StartContactStreaming to enable real-time message streaming to your SNS topic.
            #         Provide the Amazon Resource Name (ARN) of the SNS topic as part of this call
            start_contact_streaming_response = self.client.start_contact_streaming(
                InstanceId=self.instance_id,
                ContactId=contact_id,
                ChatStreamingConfiguration={
                    "StreamingEndpointArn": self.streaming_arn
                }
            )
            streaming_id = start_contact_streaming_response.get("StreamingId", None)
            self.logger.debug("StartContactStreaming response: StreamingId: '%s'",
                streaming_id)
            self.logger.debug("StartContactStreaming response: %s", start_contact_streaming_response)

        response = {
            "contact_id": contact_id,
            "participant_id": participant_id,
            "participant_token": participant_token,
            "streaming_id": streaming_id }

        # remove attribute from response with None value
        response = {k: v for k, v in response.items() if v is not None}

        self.logger.debug("Connect response: %s", response)
        return response

    def disconnect(self, contact_id: str, streaming_id: str) -> Dict[str, Any]:
        """
        Disconnect from Amazon Connect using to disable real-time chat message streaming.
        Refer to following documentation:
        https://docs.aws.amazon.com/connect/latest/APIReference/API_StopContactStreaming.html

        """
        # Call the Amazon Connect StopContactStreaming API to disable real-time message streaming.
        # Provide the StreamingId returned in the StartContactStreaming response as part of this call.
        stop_contact_streaming_response = self.client.stop_contact_streaming(
            InstanceId=self.instance_id,
            ContactId=contact_id,
            StreamingId=streaming_id
        )
        self.logger.debug("StopContactStreaming API response: %s", stop_contact_streaming_response)

        # response body is empty when call is successful.  so we return 200 status
        # code indicating operation was successful
        return {"status": 200}
